### iris データの散布図を描くプログラム例

In [71]:
%run ./iris_scatter.py

### 階層型クラスタリング
樹形図（デンドログラム）

In [72]:
%run ./hierarchical_clustering.py

### 非階層型クラスタリング
kmeans法

In [75]:
%run ./nonhierarchical_clustering.py

### 主成分分析（次元の圧縮）

In [76]:
%run ./principal-components-analysis.py

主成分 [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]
 [-0.58099728  0.59641809  0.07252408  0.54906091]
 [ 0.31725455 -0.32409435 -0.47971899  0.75112056]]
平均 [ 5.84333333  3.054       3.75866667  1.19866667]
分散 [ 4.19667516  0.24062861  0.07800042  0.02352514]
寄与率 [ 0.92461621  0.05301557  0.01718514  0.00518309]
累積寄与率 [ 0.92461621  0.97763178  0.99481691  1.        ]


### 決定木

In [78]:
%run ./decisiion_tree.py

1 [ True] [[ 0.25  0.75]]
2 [ True] [[ 0.  1.]]
3 [ True] [[ 0.25  0.75]]
4 [ True] [[ 0.25  0.75]]
5 [False] [[ 0.5  0.5]]
6 [ True] [[ 0.25  0.75]]
7 [False] [[ 1.  0.]]
8 [False] [[ 1.  0.]]
9 [False] [[ 0.5  0.5]]
10 [False] [[ 1.  0.]]


### 決定木(iris)

In [80]:
%run ./decision_tree_for_iris.py

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

Support Vector Machine

In [82]:
%run ./SVM_iris.py

/Users/user/Library/Python/3.5/lib/python/site-packages/numpy/ma/core.py:6385: MaskedArrayFutureWarning: In the future the default for ma.minimum.reduce will be axis=0, not the current None, to match np.minimum.reduce. Explicitly pass 0 or None to silence this warning.
  return self.reduce(a)
/Users/user/Library/Python/3.5/lib/python/site-packages/numpy/ma/core.py:6385: MaskedArrayFutureWarning: In the future the default for ma.maximum.reduce will be axis=0, not the current None, to match np.maximum.reduce. Explicitly pass 0 or None to silence this warning.
  return self.reduce(a)
